AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
  BrefLumen:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'bref-lumen'
      Description: ''
      CodeUri: release.zip
      Handler: public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      MemorySize: 1024 # The memory size is related to the pricing and CPU power
      Runtime: provided
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - sg-0c1914a5cfe4172cb
        SubnetIds:
          - subnet-0d7d422ac24a691c1
          - subnet-0bc04f753fdc7e546
          - subnet-043175d6a65d8c35a

      Layers:
        - 'arn:aws:lambda:eu-north-1:209497400698:layer:php-73-fpm:6'
      Environment:
        Variables:
          APP_KEY: '{{resolve:ssm:/hmazter-bref-lumen-example/APP_KEY:1}}'
          LOG_CHANNEL: stderr
      Events:
        # The function will match all HTTP URLs
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

# Outputs show up in the CloudFormation dashboard
Outputs:
  HttpApi:
    Description: 'URL of our function in the *Prod* environment'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
